/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DatasetVersionSchema extends BaseModel {
  static $columns = ['id', 'source', 'sourceVersion', 'etag', 'lastModified', 'downloadedAt', 'rowCount', 'status'] as const
  $columns = DatasetVersionSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare source: string
  @column()
  declare sourceVersion: string
  @column()
  declare etag: string | null
  @column()
  declare lastModified: string | null
  @column.dateTime()
  declare downloadedAt: DateTime
  @column()
  declare rowCount: bigint | number
  @column()
  declare status: string
}

export class LookupStatSchema extends BaseModel {
  static $columns = ['numberDigits', 'requestCount', 'found', 'operatorCode', 'riskScore', 'riskFlags', 'firstSeenAt', 'lastSeenAt'] as const
  $columns = LookupStatSchema.$columns
  @column()
  declare numberDigits: string
  @column()
  declare requestCount: bigint | number
  @column()
  declare found: boolean
  @column()
  declare operatorCode: string | null
  @column()
  declare riskScore: number
  @column()
  declare riskFlags: any
  @column.dateTime()
  declare firstSeenAt: DateTime
  @column.dateTime()
  declare lastSeenAt: DateTime
}

export class NumberRangeSchema extends BaseModel {
  static $columns = ['id', 'startNum', 'endNum', 'operatorCode', 'sourceVersion', 'createdAt', 'updatedAt'] as const
  $columns = NumberRangeSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare startNum: bigint | number
  @column()
  declare endNum: bigint | number
  @column()
  declare operatorCode: string
  @column()
  declare sourceVersion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NumberRangesStagingSchema extends BaseModel {
  static $columns = ['id', 'startNum', 'endNum', 'operatorCode', 'sourceVersion', 'createdAt', 'updatedAt'] as const
  $columns = NumberRangesStagingSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare startNum: bigint | number
  @column()
  declare endNum: bigint | number
  @column()
  declare operatorCode: string
  @column()
  declare sourceVersion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OperatorSchema extends BaseModel {
  static $columns = ['code', 'name', 'sourceVersion', 'createdAt', 'updatedAt'] as const
  $columns = OperatorSchema.$columns
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare sourceVersion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OperatorsStagingSchema extends BaseModel {
  static $columns = ['code', 'name', 'sourceVersion', 'createdAt', 'updatedAt'] as const
  $columns = OperatorsStagingSchema.$columns
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare sourceVersion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
